import {
  mdiAlertBoxOutline,
  mdiArrowDown,
  mdiArrowULeftTop,
  mdiArrowUp,
  mdiArrowURightTop,
  mdiCheckBold,
  mdiChevronDown,
  mdiChevronLeft,
  mdiClose,
  mdiCloseCircleOutline,
  mdiCloudUpload,
  mdiCogOutline,
  mdiContentCopy,
  mdiContentSave,
  mdiCrop,
  mdiCursorText,
  mdiDotsVertical,
  mdiFlagOutline,
  mdiFormatBold,
  mdiFormatClear,
  mdiFormatHeader1,
  mdiFormatHeader2,
  mdiFormatHeader3,
  mdiFormatItalic,
  mdiFormatListBulleted,
  mdiFormatListChecks,
  mdiFormatListNumbered,
  mdiFormatParagraph,
  mdiFormatQuoteOpen,
  mdiFormatStrikethrough,
  mdiFormatSuperscript,
  mdiFormatUnderline,
  mdiInformation,
  mdiLink,
  mdiLockOpenOutline,
  mdiLockOutline,
  mdiLogout,
  mdiMagnify,
  mdiMinus,
  mdiNoteEditOutline,
  mdiNotePlusOutline,
  mdiPackage,
  mdiRefresh,
  mdiTarget,
  mdiTrashCanOutline,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiXml,
} from '@mdi/js'
import { createVuetify } from 'vuetify'
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import 'vuetify/styles'

const vuetify = createVuetify({
  theme: {
    defaultTheme: 'light',
    themes: {
      light: {
        dark: false,
        primary: '#00095B',
        'node-cms-black': '#00142E',
        'node-cms-blue': '#00095B',
        'node-cms-grabber': '#1700F4',
        'node-cms-twilight': '#00142E',
        'node-cms-grey': '#AFAFAF',
        'node-cms-light-grey': '#DBDBDB',
        'node-cms-light-white-grey': '#EDEDED',
        'node-cms-off-white': '#F6F6F6',
        'node-cms-red': '#C90000',
      },
      dark: {
        dark: true,
        primary: '#FFFFFF',
        'node-cms-black': '#00142E',
        'node-cms-blue': '00142E',
        'node-cms-grabber': '00142E',
        'node-cms-twilight': '00142E',
        'node-cms-grey': '00142E',
        'node-cms-light-grey': '00142E',
        'node-cms-light-white-grey': '00142E',
        'node-cms-off-white': '00142E',
        'node-cms-red': '00142E',
      },
    },
  },
  icons: {
    defaultSet: 'mdi',
    aliases: {
      ...aliases,
      chevronDown: mdiChevronDown,
      magnify: mdiMagnify,
      noteEditOutline: mdiNoteEditOutline,
      notePlusOutline: mdiNotePlusOutline,
      checkBold: mdiCheckBold,
      trashCanOutline: mdiTrashCanOutline,
      chevronLeft: mdiChevronLeft,
      weatherSunny: mdiWeatherSunny,
      weatherNight: mdiWeatherNight,
      dotsVertical: mdiDotsVertical,
      cogOutline: mdiCogOutline,
      arrowUp: mdiArrowUp,
      arrowDown: mdiArrowDown,
      logout: mdiLogout,
      crop: mdiCrop,
      formatListChecks: mdiFormatListChecks,
      close: mdiClose,
      closeCircleOutline: mdiCloseCircleOutline,
      information: mdiInformation,
      contentCopy: mdiContentCopy,
      contentSave: mdiContentSave,
      cloudUpload: mdiCloudUpload,
      formatBold: mdiFormatBold,
      formatItalic: mdiFormatItalic,
      formatStrikethrough: mdiFormatStrikethrough,
      formatParagraph: mdiFormatParagraph,
      formatListBulleted: mdiFormatListBulleted,
      formatListNumbered: mdiFormatListNumbered,
      formatSuperscript: mdiFormatSuperscript,
      formatHeader1: mdiFormatHeader1,
      formatHeader2: mdiFormatHeader2,
      formatHeader3: mdiFormatHeader3,
      formatUnderline: mdiFormatUnderline,
      link: mdiLink,
      formatQuoteOpen: mdiFormatQuoteOpen,
      xml: mdiXml,
      formatClear: mdiFormatClear,
      minus: mdiMinus,
      arrowULeftTop: mdiArrowULeftTop,
      arrowURightTop: mdiArrowURightTop,
      refresh: mdiRefresh,
      lockOpenOutline: mdiLockOpenOutline,
      lockOutline: mdiLockOutline,
      target: mdiTarget,
      flagOutline: mdiFlagOutline,
      alertBoxOutline: mdiAlertBoxOutline,
      package: mdiPackage,
      cursorText: mdiCursorText,
    },
    sets: {
      mdi,
    },
  },
})

export default vuetify
